# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go-Research(ad599f39-d79e-4a58-b465-008cedcedd30)'
    subscriptionId: 'ad599f39-d79e-4a58-b465-008cedcedd30'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'docker'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    csmParametersFile: 'paramnetrs.json'
    deploymentMode: 'Incremental'

- task: SSH@0
  inputs:
    sshEndpoint: 'docker01'
    runOptions: 'inline'
    inline: |
      #! /bin/bash
      #remove old versions of docker
      sudo yum remove docker \
                       docker-client \
                        docker-client-latest \
                        docker-common \
                        docker-latest \
                        docker-latest-logrotate \
                        docker-logrotate \
                        docker-engine
      #SET UP THE REPOSITORY
      sudo yum install -y yum-utils \
        device-mapper-persistent-data \
        lvm2
        sudo yum-config-manager \
          --add-repo \
          https://download.docker.com/linux/centos/docker-ce.repo
      
      # INSTALL DOCKER ENGINE - COMMUNITY
          sudo yum -y install docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
      # Verify that Docker Engine - Community is installed correctly
      sudo docker run hello-world
      #Insall Git
      #yum -y install git
      #configure git in your machine
      cd ~
      git clone https://github.com/ahmedakbarov/Docker.git
      cd ~/Docker
      git remote set-url origin https://github.com/ahmedakbarov/Docker.git
      git pull origin master
      id=$[(( ( RANDOM % 99 )  + 99 ))]
      $id
      docker build -t myhellowordimage:$id ./
      docker run -d -p 5000:5000 --name myhellowordcontainer-$id myhellowordimage:$id
    readyTimeout: '20000'