# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'docker'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhdV1oZ+DMQD0/vpWShl0jm6I9iV9CDn3MKo/MFY36PHTFgYxDC8nlGQV50C9LSrCS9LJHKHc0e1Yaz1X2F2noWdmbTWHGGUcoTFpumZaSSrSu/HLuAnU0o+CX+5VJScWjsoC2RafmwuOzJRyyhWl7vsvk+CPpo56kv2J482LNNOOAhS9LZ9rBKXTu5wAPLfkSIBCtqvHTKw+AeLKoK0Q8dbXSU24qKe7DHx+r+BBp3AweVwIWDdAed5g+okNB8+Rm7XS4Fqpx+m3h/R5+fMyat0fb9NQuffUfOhxAyPyUugXPhyaupB5RudaU9UtySPf7z98STIILw9N3abrDCZdxw== rsa-key-20200312'
    sshKeySecureFile: 'ssh'