on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerahmd.azurecr.io
        username: ${{ secrets.acr_containerahmd_username }}
        password: ${{ secrets.acr_containerahmd_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t containerahmd.azurecr.io/azsk:${{ github.sha }}
        docker push containerahmd.azurecr.io/azsk:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azsk_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azsk8825 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azsk8825`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azsk8825
        container-registry-url: containerahmd.azurecr.io
        container-registry-username: ${{ secrets.acr_containerahmd_username }}
        container-registry-password: ${{ secrets.acr_containerahmd_password }}
        secret-name: azskdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: azsk8825
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerahmd.azurecr.io/azsk:${{ github.sha }}
        imagepullsecrets: |
          azskdockerauth